# Generated by Django 3.2 on 2022-11-26 03:07

import data.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(max_length=150, upload_to=data.models.csv_path, validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conditions.conditioncluster')),
            ],
        ),
    ]
