# Generated by Django 3.2 on 2022-11-26 03:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_version', models.CharField(choices=[('1', '1')], default='1', max_length=3)),
                ('in_progress', models.BooleanField(default=False)),
                ('target_url', models.URLField(default='https://www.google.com/', max_length=350)),
                ('target_company', models.CharField(blank=True, max_length=150, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.JSONField(default=dict)),
                ('row', models.JSONField(blank=True, default=list, null=True)),
                ('order', models.IntegerField()),
                ('state', models.CharField(choices=[('completed', 'completed'), ('failed', 'failed'), ('yet started', 'yet started'), ('in progress', 'in progress')], default='yet started', max_length=20)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditions.conditioncluster')),
            ],
        ),
    ]
