# Generated by Django 3.2 on 2022-11-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_auto_20221126_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioncluster',
            name='data_version',
            field=models.CharField(choices=[('1', '1')], default='1', max_length=3),
        ),
        migrations.AddField(
            model_name='conditioncluster',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conditioncluster',
            name='target_company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='conditioncluster',
            name='target_url',
            field=models.URLField(default='https://www.google.com/', max_length=350),
        ),
    ]
