# Generated by Django 3.2 on 2022-11-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0003_auto_20221126_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioncluster',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
