# Generated by Django 3.2 on 2022-11-26 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_no', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=300)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditions.conditioncluster')),
            ],
        ),
    ]
