condition_id = {
  '業種(カテゴリ)': {'農林・水産': ['industryCheckLink10',
   'industryCtgDetailedCheckArray100'],
  '食品': ['industryCheckLink11', 'industryCtgDetailedCheckArray110'],
  '建設・設備関連': ['industryCheckLink12',
   'industryCtgDetailedCheckArray120',
   'industryCtgDetailedCheckArray121',
   'industryCtgDetailedCheckArray122',
   'industryCtgDetailedCheckArray123'],
  '住宅・インテリア': ['industryCheckLink13',
   'industryCtgDetailedCheckArray130',
   'industryCtgDetailedCheckArray131',
   'industryCtgDetailedCheckArray132',
   'industryCtgDetailedCheckArray133',
   'industryCtgDetailedCheckArray134'],
  'アパレル・服飾関連': ['industryCheckLink14', 'industryCtgDetailedCheckArray140'],
  '繊維・紙・パルプ': ['industryCheckLink15',
   'industryCtgDetailedCheckArray150',
   'industryCtgDetailedCheckArray151'],
  '化学・石油': ['industryCheckLink16',
   'industryCtgDetailedCheckArray160',
   'industryCtgDetailedCheckArray161'],
  '薬品・化粧品': ['industryCheckLink17',
   'industryCtgDetailedCheckArray170',
   'industryCtgDetailedCheckArray171'],
  'ゴム・ガラス・セラミックス': ['industryCheckLink18',
   'industryCtgDetailedCheckArray180',
   'industryCtgDetailedCheckArray181',
   'industryCtgDetailedCheckArray182'],
  '鉄鋼・金属・鉱業': ['industryCheckLink19',
   'industryCtgDetailedCheckArray190',
   'industryCtgDetailedCheckArray191',
   'industryCtgDetailedCheckArray192',
   'industryCtgDetailedCheckArray193'],
  '機械': ['industryCheckLink110',
   'industryCtgDetailedCheckArray1100',
   'industryCtgDetailedCheckArray1101'],
  'プラント・エンジニアリング': ['industryCheckLink111',
   'industryCtgDetailedCheckArray1110',
   'industryCtgDetailedCheckArray1111'],
  '電子・電気・OA機器': ['industryCheckLink112',
   'industryCtgDetailedCheckArray1120',
   'industryCtgDetailedCheckArray1121',
   'industryCtgDetailedCheckArray1122',
   'industryCtgDetailedCheckArray1123',
   'industryCtgDetailedCheckArray1124',
   'industryCtgDetailedCheckArray1125'],
  '自動車・輸送用機器': ['industryCheckLink113',
   'industryCtgDetailedCheckArray1130',
   'industryCtgDetailedCheckArray1131'],
  '精密・医療機器': ['industryCheckLink114',
   'industryCtgDetailedCheckArray1140',
   'industryCtgDetailedCheckArray1141'],
  '印刷・事務機器・日用品': ['industryCheckLink115',
   'industryCtgDetailedCheckArray1150',
   'industryCtgDetailedCheckArray1151',
   'industryCtgDetailedCheckArray1152'],
  'スポーツ・玩具・ゲーム製品': ['industryCheckLink116',
   'industryCtgDetailedCheckArray1160',
   'industryCtgDetailedCheckArray1161'],
  'その他メーカー・製造関連': ['industryCheckLink117',
   'industryCtgDetailedCheckArray1170',
   'industryCtgDetailedCheckArray1171'],
  '総合商社': ['industryCheckLink20', 'industryCtgDetailedCheckArray200'],
  '商社': ['industryCheckLink21',
   'industryCtgDetailedCheckArray210',
   'industryCtgDetailedCheckArray211',
   'industryCtgDetailedCheckArray212',
   'industryCtgDetailedCheckArray213',
   'industryCtgDetailedCheckArray214',
   'industryCtgDetailedCheckArray215',
   'industryCtgDetailedCheckArray216',
   'industryCtgDetailedCheckArray217',
   'industryCtgDetailedCheckArray218',
   'industryCtgDetailedCheckArray219',
   'industryCtgDetailedCheckArray2110',
   'industryCtgDetailedCheckArray2111',
   'industryCtgDetailedCheckArray2112',
   'industryCtgDetailedCheckArray2113',
   'industryCtgDetailedCheckArray2114',
   'industryCtgDetailedCheckArray2115',
   'industryCtgDetailedCheckArray2116',
   'industryCtgDetailedCheckArray2117',
   'industryCtgDetailedCheckArray2118',
   'industryCtgDetailedCheckArray2119',
   'industryCtgDetailedCheckArray2120',
   'industryCtgDetailedCheckArray2121'],
  '百貨店・スーパー・コンビニ': ['industryCheckLink30',
   'industryCtgDetailedCheckArray300',
   'industryCtgDetailedCheckArray301',
   'industryCtgDetailedCheckArray302',
   'industryCtgDetailedCheckArray303',
   'industryCtgDetailedCheckArray304'],
  '専門店': ['industryCheckLink31',
   'industryCtgDetailedCheckArray310',
   'industryCtgDetailedCheckArray311',
   'industryCtgDetailedCheckArray312',
   'industryCtgDetailedCheckArray313',
   'industryCtgDetailedCheckArray314',
   'industryCtgDetailedCheckArray315',
   'industryCtgDetailedCheckArray316',
   'industryCtgDetailedCheckArray317',
   'industryCtgDetailedCheckArray318',
   'industryCtgDetailedCheckArray319'],
  '銀行・証券': ['industryCheckLink40',
   'industryCtgDetailedCheckArray400',
   'industryCtgDetailedCheckArray401',
   'industryCtgDetailedCheckArray402',
   'industryCtgDetailedCheckArray403',
   'industryCtgDetailedCheckArray404',
   'industryCtgDetailedCheckArray405',
   'industryCtgDetailedCheckArray406'],
  '信金・労金・信組': ['industryCheckLink41', 'industryCtgDetailedCheckArray410'],
  'クレジット・信販・リース・その他金融': ['industryCheckLink42',
   'industryCtgDetailedCheckArray420',
   'industryCtgDetailedCheckArray421',
   'industryCtgDetailedCheckArray422',
   'industryCtgDetailedCheckArray423',
   'industryCtgDetailedCheckArray424',
   'industryCtgDetailedCheckArray425',
   'industryCtgDetailedCheckArray426'],
  '生保・損保': ['industryCheckLink43',
   'industryCtgDetailedCheckArray430',
   'industryCtgDetailedCheckArray431'],
  '不動産': ['industryCheckLink50',
   'industryCtgDetailedCheckArray500',
   'industryCtgDetailedCheckArray501'],
  '鉄道・航空': ['industryCheckLink51',
   'industryCtgDetailedCheckArray510',
   'industryCtgDetailedCheckArray511',
   'industryCtgDetailedCheckArray512'],
  '陸運・海運・物流': ['industryCheckLink52',
   'industryCtgDetailedCheckArray520',
   'industryCtgDetailedCheckArray521',
   'industryCtgDetailedCheckArray522'],
  '電力・ガス・エネルギー': ['industryCheckLink53',
   'industryCtgDetailedCheckArray530',
   'industryCtgDetailedCheckArray531'],
  'レストラン・給食・フードサービス': ['industryCheckLink54',
   'industryCtgDetailedCheckArray540',
   'industryCtgDetailedCheckArray541'],
  'ホテル・旅行': ['industryCheckLink55',
   'industryCtgDetailedCheckArray550',
   'industryCtgDetailedCheckArray551'],
  '医療機関・調剤薬局': ['industryCheckLink56',
   'industryCtgDetailedCheckArray560',
   'industryCtgDetailedCheckArray561'],
  '福祉サービス': ['industryCheckLink57', 'industryCtgDetailedCheckArray570'],
  'フィットネスクラブ・エステ・理美容': ['industryCheckLink58',
   'industryCtgDetailedCheckArray580',
   'industryCtgDetailedCheckArray581',
   'industryCtgDetailedCheckArray582'],
  'アミューズメント・レジャー': ['industryCheckLink59',
   'industryCtgDetailedCheckArray590',
   'industryCtgDetailedCheckArray591'],
  '冠婚葬祭': ['industryCheckLink510', 'industryCtgDetailedCheckArray5100'],
  '専門・その他サービス': ['industryCheckLink511',
   'industryCtgDetailedCheckArray5110',
   'industryCtgDetailedCheckArray5111',
   'industryCtgDetailedCheckArray5112',
   'industryCtgDetailedCheckArray5113',
   'industryCtgDetailedCheckArray5114',
   'industryCtgDetailedCheckArray5115',
   'industryCtgDetailedCheckArray5116',
   'industryCtgDetailedCheckArray5117',
   'industryCtgDetailedCheckArray5118'],
  'コンサルティング・シンクタンク・調査': ['industryCheckLink512',
   'industryCtgDetailedCheckArray5120',
   'industryCtgDetailedCheckArray5121',
   'industryCtgDetailedCheckArray5122'],
  '人材サービス（派遣・紹介）': ['industryCheckLink513',
   'industryCtgDetailedCheckArray5130'],
  '教育': ['industryCheckLink514',
   'industryCtgDetailedCheckArray5140',
   'industryCtgDetailedCheckArray5141',
   'industryCtgDetailedCheckArray5142'],
  'ソフトウエア・情報処理・ネット関連': ['industryCheckLink60',
   'industryCtgDetailedCheckArray600',
   'industryCtgDetailedCheckArray601',
   'industryCtgDetailedCheckArray602'],
  'ゲームソフト': ['industryCheckLink61', 'industryCtgDetailedCheckArray610'],
  '通信': ['industryCheckLink62',
   'industryCtgDetailedCheckArray620',
   'industryCtgDetailedCheckArray621'],
  'マスコミ（放送・新聞）': ['industryCheckLink70',
   'industryCtgDetailedCheckArray700',
   'industryCtgDetailedCheckArray701'],
  'マスコミ（出版・広告）': ['industryCheckLink71',
   'industryCtgDetailedCheckArray710',
   'industryCtgDetailedCheckArray711',
   'industryCtgDetailedCheckArray712'],
  '芸能・映画・音楽': ['industryCheckLink72', 'industryCtgDetailedCheckArray720'],
  '官公庁・公社・団体': ['industryCheckLink80',
   'industryCtgDetailedCheckArray800',
   'industryCtgDetailedCheckArray801',
   'industryCtgDetailedCheckArray802',
   'industryCtgDetailedCheckArray803']},
 '業種(詳細)': {'農林・水産': 'industryCtgDetailedCheckArray100',
  '食品': 'industryCtgDetailedCheckArray110',
  '建設': 'industryCtgDetailedCheckArray120',
  '設備工事': 'industryCtgDetailedCheckArray121',
  '建築設計': 'industryCtgDetailedCheckArray122',
  '建設コンサルタント': 'industryCtgDetailedCheckArray123',
  '住宅': 'industryCtgDetailedCheckArray130',
  '住宅（リフォーム）': 'industryCtgDetailedCheckArray131',
  '建材・エクステリア': 'industryCtgDetailedCheckArray132',
  'インテリア・住宅関連': 'industryCtgDetailedCheckArray133',
  '空間デザイン・ディスプレイ': 'industryCtgDetailedCheckArray134',
  'アパレル（メーカー）': 'industryCtgDetailedCheckArray140',
  '繊維': 'industryCtgDetailedCheckArray150',
  '紙・パルプ': 'industryCtgDetailedCheckArray151',
  '化学': 'industryCtgDetailedCheckArray160',
  '石油': 'industryCtgDetailedCheckArray161',
  '薬品': 'industryCtgDetailedCheckArray170',
  '化粧品': 'industryCtgDetailedCheckArray171',
  'タイヤ・ゴム製品': 'industryCtgDetailedCheckArray180',
  'セメント': 'industryCtgDetailedCheckArray181',
  'ガラス・セラミックス': 'industryCtgDetailedCheckArray182',
  '鉱業': 'industryCtgDetailedCheckArray190',
  '鉄鋼': 'industryCtgDetailedCheckArray191',
  '非鉄金属': 'industryCtgDetailedCheckArray192',
  '金属製品': 'industryCtgDetailedCheckArray193',
  '機械': 'industryCtgDetailedCheckArray1100',
  '機械設計': 'industryCtgDetailedCheckArray1101',
  'プラント・エンジニアリング': 'industryCtgDetailedCheckArray1110',
  '環境・リサイクル': 'industryCtgDetailedCheckArray1111',
  '総合電機': 'industryCtgDetailedCheckArray1120',
  '重電・産業用電気機器': 'industryCtgDetailedCheckArray1121',
  '家電・ＡＶ機器': 'industryCtgDetailedCheckArray1122',
  '半導体・電子・電気機器': 'industryCtgDetailedCheckArray1123',
  'その他電子・電気関連': 'industryCtgDetailedCheckArray1124',
  'コンピュータ・通信機器': 'industryCtgDetailedCheckArray1125',
  '輸送用機器': 'industryCtgDetailedCheckArray1130',
  '自動車・自動車部品': 'industryCtgDetailedCheckArray1131',
  '精密機器': 'industryCtgDetailedCheckArray1140',
  '医療用機器・医療関連': 'industryCtgDetailedCheckArray1141',
  '印刷・印刷関連': 'industryCtgDetailedCheckArray1150',
  '文具・事務機器関連': 'industryCtgDetailedCheckArray1151',
  '日用品・生活関連機器': 'industryCtgDetailedCheckArray1152',
  'ゲーム・玩具・アミューズメント製品': 'industryCtgDetailedCheckArray1160',
  'スポーツ・レジャー用品（メーカー）': 'industryCtgDetailedCheckArray1161',
  'その他メーカー': 'industryCtgDetailedCheckArray1170',
  '受託開発': 'industryCtgDetailedCheckArray1171',
  '総合商社': 'industryCtgDetailedCheckArray200',
  '商社（複合）': 'industryCtgDetailedCheckArray210',
  '商社（食品・農林・水産）': 'industryCtgDetailedCheckArray211',
  '商社（インテリア・住宅関連）': 'industryCtgDetailedCheckArray212',
  '商社（建材）': 'industryCtgDetailedCheckArray213',
  '商社（アパレル・ファッション関連）': 'industryCtgDetailedCheckArray214',
  '商社（紙・パルプ）': 'industryCtgDetailedCheckArray215',
  '商社（化学・石油・ガス・電気）': 'industryCtgDetailedCheckArray216',
  '商社（薬品・化粧品）': 'industryCtgDetailedCheckArray217',
  '商社（鉄鋼・金属）': 'industryCtgDetailedCheckArray218',
  '商社（機械・プラント・環境）': 'industryCtgDetailedCheckArray219',
  '商社（電子・電気機器）': 'industryCtgDetailedCheckArray2110',
  '商社（自動車関連・輸送用機器）': 'industryCtgDetailedCheckArray2111',
  '商社（精密・医療機器）': 'industryCtgDetailedCheckArray2112',
  '商社（通信）': 'industryCtgDetailedCheckArray2113',
  '商社（ソフトウェア）': 'industryCtgDetailedCheckArray2114',
  '商社（文具・OA関連・日用品）': 'industryCtgDetailedCheckArray2115',
  '商社（出版）': 'industryCtgDetailedCheckArray2116',
  '商社（スポーツ・レジャー用品）': 'industryCtgDetailedCheckArray2117',
  '商社（教育関連）': 'industryCtgDetailedCheckArray2118',
  '商社（グループ）': 'industryCtgDetailedCheckArray2119',
  '商社（その他製品）': 'industryCtgDetailedCheckArray2120',
  '通販・ネット販売': 'industryCtgDetailedCheckArray2121',
  '百貨店': 'industryCtgDetailedCheckArray300',
  'スーパーマーケット': 'industryCtgDetailedCheckArray301',
  'コンビニエンスストア': 'industryCtgDetailedCheckArray302',
  'ホームセンター': 'industryCtgDetailedCheckArray303',
  '生活協同組合': 'industryCtgDetailedCheckArray304',
  'ドラッグストア': 'industryCtgDetailedCheckArray310',
  '専門店（複合）': 'industryCtgDetailedCheckArray311',
  '専門店（家電・OA機器）': 'industryCtgDetailedCheckArray312',
  '専門店（メガネ・貴金属・ジュエリー）': 'industryCtgDetailedCheckArray313',
  '専門店（食品・日用品）': 'industryCtgDetailedCheckArray314',
  '専門店（アパレル・ファッション関連）': 'industryCtgDetailedCheckArray315',
  '専門店（自動車関連）': 'industryCtgDetailedCheckArray316',
  '専門店（書籍・音楽・インテリア）': 'industryCtgDetailedCheckArray317',
  '専門店（スポーツ関連）': 'industryCtgDetailedCheckArray318',
  '専門店（その他小売）': 'industryCtgDetailedCheckArray319',
  '政府系・系統金融機関': 'industryCtgDetailedCheckArray400',
  '金融総合グループ': 'industryCtgDetailedCheckArray401',
  '銀行（都銀）': 'industryCtgDetailedCheckArray402',
  '銀行（地銀）': 'industryCtgDetailedCheckArray403',
  '銀行（ネットバンク・その他）': 'industryCtgDetailedCheckArray404',
  '信託銀行・投資銀行・投資信託委託': 'industryCtgDetailedCheckArray405',
  '証券': 'industryCtgDetailedCheckArray406',
  '信用金庫・労働金庫・信用組合': 'industryCtgDetailedCheckArray410',
  '外資系金融': 'industryCtgDetailedCheckArray420',
  'クレジット・信販': 'industryCtgDetailedCheckArray421',
  '共済': 'industryCtgDetailedCheckArray422',
  'リース・レンタル': 'industryCtgDetailedCheckArray423',
  '消費者金融': 'industryCtgDetailedCheckArray424',
  '商品取引': 'industryCtgDetailedCheckArray425',
  'その他金融': 'industryCtgDetailedCheckArray426',
  '損害保険': 'industryCtgDetailedCheckArray430',
  '生命保険': 'industryCtgDetailedCheckArray431',
  '不動産': 'industryCtgDetailedCheckArray500',
  '不動産（管理）': 'industryCtgDetailedCheckArray501',
  '鉄道': 'industryCtgDetailedCheckArray510',
  '空輸': 'industryCtgDetailedCheckArray511',
  '空港サービス': 'industryCtgDetailedCheckArray512',
  '陸運（貨物・バス・タクシー）': 'industryCtgDetailedCheckArray520',
  '海運': 'industryCtgDetailedCheckArray521',
  '物流・倉庫': 'industryCtgDetailedCheckArray522',
  '電力': 'industryCtgDetailedCheckArray530',
  'ガス・エネルギー': 'industryCtgDetailedCheckArray531',
  '外食・レストラン': 'industryCtgDetailedCheckArray540',
  '給食・デリカ・フードビジネス': 'industryCtgDetailedCheckArray541',
  'ホテル・旅館': 'industryCtgDetailedCheckArray550',
  '旅行・観光': 'industryCtgDetailedCheckArray551',
  '調剤薬局': 'industryCtgDetailedCheckArray560',
  '医療機関': 'industryCtgDetailedCheckArray561',
  '福祉サービス': 'industryCtgDetailedCheckArray570',
  'フィットネスクラブ': 'industryCtgDetailedCheckArray580',
  'エステティック・美容・理容': 'industryCtgDetailedCheckArray581',
  'マッサージ・整体・鍼灸': 'industryCtgDetailedCheckArray582',
  'レジャーサービス': 'industryCtgDetailedCheckArray590',
  'アミューズメント': 'industryCtgDetailedCheckArray591',
  '冠婚葬祭': 'industryCtgDetailedCheckArray5100',
  'ビル施設管理・メンテナンス': 'industryCtgDetailedCheckArray5110',
  'セキュリティ': 'industryCtgDetailedCheckArray5111',
  '芸術関連': 'industryCtgDetailedCheckArray5112',
  '各種ビジネスサービス・BPO': 'industryCtgDetailedCheckArray5113',
  'フォトサービス': 'industryCtgDetailedCheckArray5114',
  'クリーニング': 'industryCtgDetailedCheckArray5115',
  'イベント・興行': 'industryCtgDetailedCheckArray5116',
  '検査・整備・メンテナンス': 'industryCtgDetailedCheckArray5117',
  'サービス（その他）': 'industryCtgDetailedCheckArray5118',
  'シンクタンク・マーケティング・調査': 'industryCtgDetailedCheckArray5120',
  '専門コンサルティング': 'industryCtgDetailedCheckArray5121',
  'コンサルティングファーム': 'industryCtgDetailedCheckArray5122',
  '人材派遣・人材紹介': 'industryCtgDetailedCheckArray5130',
  '教育': 'industryCtgDetailedCheckArray5140',
  '学校法人': 'industryCtgDetailedCheckArray5141',
  '幼稚園・保育園': 'industryCtgDetailedCheckArray5142',
  'ソフトウエア': 'industryCtgDetailedCheckArray600',
  '情報処理': 'industryCtgDetailedCheckArray601',
  'インターネット関連': 'industryCtgDetailedCheckArray602',
  'ゲームソフト': 'industryCtgDetailedCheckArray610',
  '通信・インフラ': 'industryCtgDetailedCheckArray620',
  'ニュース・データ通信': 'industryCtgDetailedCheckArray621',
  '放送': 'industryCtgDetailedCheckArray700',
  '新聞': 'industryCtgDetailedCheckArray701',
  '出版': 'industryCtgDetailedCheckArray710',
  '広告': 'industryCtgDetailedCheckArray711',
  'Web制作': 'industryCtgDetailedCheckArray712',
  '芸能・映画・音楽': 'industryCtgDetailedCheckArray720',
  '農業協同組合（JA金融機関含む）': 'industryCtgDetailedCheckArray800',
  '公益・特殊・独立行政法人': 'industryCtgDetailedCheckArray801',
  '官公庁・警察': 'industryCtgDetailedCheckArray802',
  '財団・社団・その他団体': 'industryCtgDetailedCheckArray803'},
 '地域': {'北海道': 'ifRegional510',
  '青森': 'ifRegional511',
  '岩手': 'ifRegional512',
  '宮城': 'ifRegional513',
  '秋田': 'ifRegional514',
  '山形': 'ifRegional515',
  '福島': 'ifRegional516',
  '茨城': 'ifRegional520',
  '栃木': 'ifRegional521',
  '群馬': 'ifRegional522',
  '埼玉': 'ifRegional523',
  '千葉': 'ifRegional524',
  '東京': 'ifRegional525',
  '神奈川': 'ifRegional526',
  '新潟': 'ifRegional530',
  '富山': 'ifRegional531',
  '石川': 'ifRegional532',
  '福井': 'ifRegional533',
  '山梨': 'ifRegional534',
  '長野': 'ifRegional535',
  '岐阜': 'ifRegional540',
  '静岡': 'ifRegional541',
  '愛知': 'ifRegional542',
  '三重': 'ifRegional543',
  '滋賀': 'ifRegional550',
  '京都': 'ifRegional551',
  '大阪': 'ifRegional552',
  '兵庫': 'ifRegional553',
  '奈良': 'ifRegional554',
  '和歌山': 'ifRegional555',
  '鳥取': 'ifRegional560',
  '島根': 'ifRegional561',
  '岡山': 'ifRegional562',
  '広島': 'ifRegional563',
  '山口': 'ifRegional564',
  '徳島': 'ifRegional565',
  '香川': 'ifRegional566',
  '愛媛': 'ifRegional567',
  '高知': 'ifRegional568',
  '福岡': 'ifRegional570',
  '佐賀': 'ifRegional571',
  '長崎': 'ifRegional572',
  '熊本': 'ifRegional573',
  '大分': 'ifRegional574',
  '宮崎': 'ifRegional575',
  '鹿児島': 'ifRegional576',
  '沖縄': 'ifRegional577',
  '海外': 'ifRegional590'},
 '職種': {'総務・人事・労務': 'occGroup00',
  '経理・財務・会計': 'occGroup01',
  '法務・特許・審査': 'occGroup02',
  '貿易事務・海外事務': 'occGroup03',
  '物流・在庫管理': 'occGroup04',
  '秘書・受付': 'occGroup05',
  '一般事務・営業事務・アシスタント': 'occGroup06',
  '医療事務': 'occGroup07',
  '宣伝・広報': 'occGroup10',
  '調査研究・マーケティング': 'occGroup11',
  '経営企画': 'occGroup12',
  '企画・商品開発': 'occGroup13',
  '営業(個人向け新規開拓メイン)': 'occGroup20',
  '営業(個人向け既存顧客メイン)': 'occGroup21',
  '営業(法人向け新規開拓メイン)': 'occGroup22',
  '営業(法人向け既存顧客メイン)': 'occGroup23',
  '海外営業': 'occGroup24',
  '営業推進・販売促進': 'occGroup25',
  'MR（医薬情報担当者）': 'occGroup26',
  'カスタマーサポート・カスタマーサクセス': 'occGroup27',
  '技術営業・システム営業': 'occGroup28',
  '基礎研究': 'occGroup30',
  '応用研究・技術開発': 'occGroup31',
  '生産・製造技術': 'occGroup32',
  '機械・電子機器設計': 'occGroup33',
  '品質・生産管理・メンテナンス': 'occGroup34',
  '建築／建築設備': 'occGroup35',
  '土木施工／測量／積算': 'occGroup36',
  '施工管理': 'occGroup37',
  '調理師・調理補助': 'occGroup40',
  '販売スタッフ・接客': 'occGroup41',
  '店長(店舗運営など)': 'occGroup42',
  'スーパーバイザー': 'occGroup43',
  'バイヤー': 'occGroup44',
  'エステティシャン': 'occGroup45',
  '客室乗務員・パーサー': 'occGroup46',
  'ドライバー': 'occGroup47',
  '美容部員': 'occGroup48',
  '店舗開発': 'occGroup49',
  '経営コンサルタント': 'occGroup50',
  '専門コンサルタント': 'occGroup51',
  '栄養士': 'occGroup52',
  '管理栄養士': 'occGroup53',
  'アナウンサー': 'occGroup54',
  'インテリアコーディネーター': 'occGroup55',
  'カラーリスト': 'occGroup56',
  'ブライダルコーディネーター': 'occGroup57',
  '税理士・公認会計士': 'occGroup58',
  '薬剤師': 'occGroup60',
  '看護師': 'occGroup61',
  '理学療法士': 'occGroup62',
  '作業療法士': 'occGroup63',
  '言語聴覚士': 'occGroup64',
  '視能訓練士': 'occGroup65',
  '臨床工学技士': 'occGroup66',
  '歯科衛生士': 'occGroup67',
  '臨床検査技師': 'occGroup68',
  '診療放射線技師': 'occGroup69',
  '社会福祉士': 'occGroup610',
  '精神保健福祉士': 'occGroup611',
  '介護福祉士': 'occGroup612',
  '介護職・ヘルパー': 'occGroup613',
  '医療ソーシャルワーカー': 'occGroup614',
  'マッサージ師・はり師': 'occGroup615',
  '公認心理士・臨床心理士': 'occGroup616',
  '為替ディーラー・トレーダー': 'occGroup70',
  '融資・資産運用マネージャー': 'occGroup71',
  '証券アナリスト': 'occGroup72',
  'アクチュアリー': 'occGroup73',
  'ファイナンシャルアドバイザー': 'occGroup74',
  '編集・制作': 'occGroup80',
  '記者・ライター': 'occGroup81',
  'ゲームクリエイター': 'occGroup82',
  'ファッションデザイナー・パタンナー': 'occGroup83',
  'ジュエリーデザイナー': 'occGroup84',
  'ＣＧデザイナー': 'occGroup85',
  'グラフィックデザイナー': 'occGroup86',
  'インダストリアルデザイナー': 'occGroup87',
  '空間デザイナー': 'occGroup88',
  'フォトグラファー': 'occGroup89',
  '広告デザイナー': 'occGroup810',
  'ＷＥＢデザイナー': 'occGroup811',
  'WEBプロデューサー・ディレクター': 'occGroup812',
  'ITコンサルタント': 'occGroup90',
  'データサイエンティスト': 'occGroup91',
  'プログラマー': 'occGroup92',
  'ネットワークエンジニア': 'occGroup93',
  'システム保守運用': 'occGroup94',
  'システムコンサルタント': 'occGroup95',
  'カスタマーエンジニア': 'occGroup96',
  'システムエンジニア': 'occGroup97',
  'セールスエンジニア': 'occGroup98',
  '講師・インストラクター': 'occGroup100',
  '警備員': 'occGroup101',
  '警察官・自衛官': 'occGroup102',
  '消防士': 'occGroup103',
  '保育士': 'occGroup104',
  '幼稚園教諭': 'occGroup105',
  'ＯＡインストラクター': 'occGroup106',
  'スポーツインストラクター': 'occGroup107',
  '国家公務員': 'occGroup108',
  '地方公務員': 'occGroup109',
  '教師': 'occGroup1010',
  '学芸員・司書': 'occGroup1011',
  'その他公務員・団体職員': 'occGroup1012'},
 '福利厚生': {'30歳平均年収が600万円以上': 'corpWelfare0',
  '実力主義の給与体系・評価制度を導入': 'corpWelfare1',
  '年間休日120日以上': 'corpWelfare2',
  '福利厚生が充実': 'corpWelfare3',
  'ジョブローテーションで様々な職種を体験できる': 'corpWelfare4',
  '教育・研修制度が充実': 'corpWelfare5',
  '資格取得支援制度あり': 'corpWelfare6',
  '独立・起業支援制度あり': 'corpWelfare7',
  '時短勤務制度あり': 'corpWelfare8',
  '産休・育児休暇取得実績あり': 'corpWelfare9',
  '平均残業時間が月20時間以内': 'corpWelfare10',
  '完全週休2日制': 'corpWelfare11',
  '社宅・家賃補助制度あり': 'corpWelfare12'},
 '従業員数': {'～ 50人未満': 'empInfo0',
  '50 ～ 100人未満': 'empInfo1',
  '100 ～ 300人未満': 'empInfo2',
  '300 ～ 500人未満': 'empInfo3',
  '500 ～ 1000人未満': 'empInfo4',
  '1000 ～ 3000人未満': 'empInfo5',
  '3000 ～ 5000人未満': 'empInfo6',
  '5000人以上': 'empInfo7'},
 '選考の特徴': {'選考でエントリーシートなし': 'selectionFeatureVar0',
  '選考で筆記・適性検査なし': 'selectionFeatureVar1',
  '選考でグループワーク・グループディスカッションなし': 'selectionFeatureVar2',
  'グループ面接なし': 'selectionFeatureVar3'},
 '募集の特徴': {'総合職採用': 'recruitingFeatureVar0',
  '一般職採用': 'recruitingFeatureVar1',
  '説明会・選考にて交通費支給あり': 'recruitingFeatureVar2',
  '説明会・選考にて宿泊費支給あり': 'recruitingFeatureVar3',
  '海外留学経験のある学生を積極採用': 'recruitingFeatureVar4',
  '留学生を積極採用': 'recruitingFeatureVar5',
  '既卒者を積極採用': 'recruitingFeatureVar6',
  '障がい者向けコースあり': 'recruitingFeatureVar7',
  '内々定まで1カ月以内': 'recruitingFeatureVar8',
  'エリア限定勤務（エリア限定職採用）あり': 'recruitingFeatureVar9'},
 '募集対象': {'理系大学院生': 'recruitingTgtVar0',
  '理系学部生': 'recruitingTgtVar1',
  '文系大学院生': 'recruitingTgtVar2',
  '文系学部生': 'recruitingTgtVar3',
  '短大生': 'recruitingTgtVar4',
  '高専生': 'recruitingTgtVar5',
  '専門学校生': 'recruitingTgtVar6',
  '既卒者': 'recruitingTgtVar7'},
 '募集人数': {'若干名': 'crpRecruitingCntCtg0',
  '1～5名': 'crpRecruitingCntCtg1',
  '6～10名': 'crpRecruitingCntCtg2',
  '11～15名': 'crpRecruitingCntCtg3',
  '16～20名': 'crpRecruitingCntCtg4',
  '21～25名': 'crpRecruitingCntCtg5',
  '26～30名': 'crpRecruitingCntCtg6',
  '31～35名': 'crpRecruitingCntCtg7',
  '36～40名': 'crpRecruitingCntCtg8',
  '41～45名': 'crpRecruitingCntCtg9',
  '46～50名': 'crpRecruitingCntCtg10',
  '51～100名': 'crpRecruitingCntCtg11',
  '101～200名': 'crpRecruitingCntCtg12',
  '201～300名': 'crpRecruitingCntCtg13',
  '301名～': 'crpRecruitingCntCtg14'},
 '受付状況': {'新着': 'receptionStatus1',
  'My CareerBoxで応募可': 'receptionStatus4',
  'インターンシップ・仕事体験あり': 'receptionStatus5'}
}

conditions = list(condition_id.keys())